- name: Creating btc-usdt-binance hummingbot directory
  file:
    path: /home/{{ hbadmin }}/btc-usdt-binance/
    state: directory
    owner: "{{ hbadmin }}"

- name: Download create.sh
  get_url:
    url: https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/docker-commands/create.sh
    dest: /home/{{ hbadmin }}/btc-usdt-binance
    mode: a+x
    owner: "{{ hbadmin}}"

- name: Download start.sh
  get_url:
    url: https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/docker-commands/start.sh
    dest: /home/{{ hbadmin }}/btc-usdt-binance
    mode: a+x
    owner: "{{ hbadmin }}"

- name: Download update.sh
  get_url:
    url: https://raw.githubusercontent.com/CoinAlpha/hummingbot/development/installation/docker-commands/update.sh
    dest: /home/{{ hbadmin }}/btc-usdt-binance
    mode: a+x
    owner: "{{ hbadmin }}"

- name: Create btc_usdt-binance_files  directory if it does not exist
  file:
    path: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/
    state: directory
    mode: '0755'
    owner: "{{ hbadmin }}"

    #- name: Create btc-usdt-binance_files/hummingbot_conf  directory if it does not exist
    #file:
      #path: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/hummingbot_conf
      #state: directory
      #mode: a+rw
      #owner: "{{ hbadmin }}"

- name: Create btc-usdt-binance_files/hummingbot_logs  directory if it does not exist
  file:
    path: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/hummingbot_logs
    state: directory
    mode: '0755'
    owner: "{{ hbadmin }}"

- name: Create btc-usdt-binance_files/hummingbot_data  directory if it does no
  file:
    path: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/hummingbot_data
    state: directory
    mode: '0755'
    owner: "{{ hbadmin }}"

    #- name: Create hummingbot_files/hummingbot_scripts  directory if it does no
    #file:
      # path: /root/dash-btc-binance/dash-btc-binance_files/hummingbot_scripts
      #state: directory
      #mode: '0755'

- synchronize:
    src: btc-usdt-binance/configs/
    dest: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/hummingbot_conf/
   #  owner: "{{ hbadmin }}"
- synchronize:
    src: btc-usdt-binance/
    dest: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/
    #owner: "{{ hbadmin }}"


    #- name: write btc-usdt-binance config files (global and strategy)
    #copy:
      #src: btc-usdt-binance/configs
      #dest: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files/hummingbot_conf #"{{ dashconf_file_path }}"
      #owner: "{{ hbadmin }}"
    #when: not dashconf_file.stat.exists
    #
    #- name: write btc-usdt-binance script directory/files
    #copy:
      #src: btc-usdt-binance/hummingbot_scripts
      #dest: /home/{{ hbadmin }}/btc-usdt-binance/btc-usdt-binance_files
      #owner: "{{ hbadmin }}"
    #when: not dashconf_file.stat.exists

