- name: Update package cache
  package: update_cache=yes cache_valid_time=3600
  changed_when: False

- name: Upgrade to the latest packages
  package: upgrade=safe
  changed_when: False

- name: Install Tmux
  package:
    name: tmux
    state: present

- name: Install Docker
  package:
    name: docker.io
    state: present

- name: Install pip
  package:
    name: python3-pip
    state: present

    #- name: Install docker-py for ansible docker conatiner
    #package:
      #name: docker-py
      #state: present


- name: Start & Enable Docker
  systemd:
    state: started
    name: docker
    enabled: yes

- name: Allow docker commands without requiring sudo prefix
  shell: sudo usermod -a -G docker {{ hb }} #$USER
